interface=eth0
bind-dynamic
port=0
dhcp-authoritative
dhcp-range=10.77.0.50,10.77.0.100,255.255.255.0,12h
dhcp-host=b0:e8:92:fc:dd:26,10.77.0.85,Printer-FCDD26,infinite
dhcp-option=option:router,10.77.0.1
log-dhcp
